steps:
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
args:
  - gcloud
  - functions
  - deploy
  - funkyPubSub
  - --region=us-central1
  - --source=.
  - --trigger-topic
  - --runtime=java17
  - --entry-point com.zinkworks.bountyhuntersurlshortener.google.HttpFunctions
  - --no-cache