steps:
# Build the container image
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/url-shortener-417915/docker.io/clynam/vol1', '.']
# Push the container image to Container Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/url-shortener-417915/docker.io/clynam/vol1']
# Deploy container image to Cloud Run
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args: ['run', 'deploy', 'urlshort', '--image', 'gcr.io/url-shortener-417915/docker.io/clynam/vol1', '--region', 'europe-west10', "./backend"]
images:
  - gcr.io/url-shortener-417915/docker.io/clynam/vol1