apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: urlshort
  namespace: url-shortener-417915
  labels:
    cloud.googleapis.com/location: europe-west4-a
    annotations:
      run.googleapis.com/launch-stage: BETA
      run.googleapis.com/description: UrlShortener
      run.googleapis.com/ingress: all
      run.googleapis.com/binary-authorization: default

spec:
  template:
    metadata:
      name: urlshort
      annotations:
        autoscaling.knative.dev/minScale: 1
        autoscaling.knative.dev/maxScale: 10
        run.googleapis.com/cpu-throttling: false
        run.googleapis.com/startup-cpu-boost: 1
        run.googleapis.com/sessionAffinity: true
        run.googleapis.com/cloudsql-instances: url-shortener-417915:europe-west4:mypostgres
        run.googleapis.com/execution-environment: gen1
        run.googleapis.com/minScale: 0
    spec:
      serviceAccountName: sqlbadboy@url-shortener-417915.iam.gserviceaccount.com
      containers:
        - image: gcr.io/url-shortener/urlshort
          name: urlshort
          command:
            - COMMAND1
            - COMMAND2
          args:
            - ARGUMENT1
            - ARGUMENT2
          ports:
            - name: HTTP1_OR_H2C
              containerPort: PORT
          env:
            - name: KEY
              value: VALUE
          resources:
            limits:
              cpu: CPU_LIMIT
              memory: MEMORY_LIMIT
          volumeMounts:
            - name: VOLUME_NAME
              mountPath: MOUNT_PATH
          startupProbe:
            httpGet:
              path: CHECK_PATH
              httpHeaders:
                - name: HEADER_NAME
                  value: HEADER_VALUE
              port: PORT
            tcpSocket:
              port: PORT
            grpc:
              service: GRPC_SERVICE
              port: PORT
            initialDelaySeconds: DELAY
            timeoutSeconds: TIMEOUT
            failureThreshold: THRESHOLD
            periodSeconds: PERIOD
          livenessProbe:
            httpGet:
              path: CHECK_PATH
              port: PORT
              httpHeaders:
                - name: HEADER_NAME
                  value: HEADER_VALUE
            grpc:
              service: GRPC_SERVICE
              port: PORT
            initialDelaySeconds: DELAY
            timeoutSeconds: TIMEOUT
            failureThreshold: THRESHOLD
            periodSeconds: PERIOD
        - image: SIDECAR_IMAGE
          name: SIDECAR_NAME
      volumes:
        - name: VOLUME_NAME
          secret:
            secretName: SECRET
            items:
              - key: SECRET_VERSION
                path: PATH
        - name: VOLUME_NAME
          emptyDir:
            sizeLimit: IN_MEMORY_VOLUME_SIZE
            medium: Memory
        - name: VOLUME_NAME
          csi:
            driver: gcsfuse.run.googleapis.com
            readOnly: IS_READ_ONLY
            volumeAttributes:
              bucketName: BUCKET_NAME
        - name: VOLUME_NAME
          nfs:
            server: IP_ADDRESS
            path: NFS_PATH
            readonly: IS_READ_ONLY
      traffic:
        - percent: PERCENT_TO_LATEST
          latestRevision: true
        - percent: PERCENT_TO_REVISION
          revisionName: REVISION_NAME
        - tag: TAG
          revisionName: REVISION_NAME