steps:
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    args:
      - gcloud
      - functions
      - deploy
      - url-http-function
      - --region=us-central1
      - --source=.
      - --trigger-http
      - --runtime=java17
      - --entry-point com.GcpExercies.GcpExercies.Ex1.HttpFunctions
      - --no-cache